-- Enable Row Level Security (RLS) is generally recommended, 
-- but for this initial setup we will keep it simple. 
-- You might want to enable RLS policies later for security.

-- 1. Products Table
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  description text,
  price numeric not null,
  available boolean default true,
  image_url text
);

-- 2. Settings Table (Single row)
create table public.settings (
  id bigint generated by default as identity primary key,
  app_name text,
  whatsapp_number text,
  delivery_enabled boolean default true,
  eat_in_enabled boolean default true,
  total_orders integer default 0,
  total_revenue numeric default 0
);

-- Insert default settings row if not exists
insert into public.settings (id, app_name, whatsapp_number, delivery_enabled, eat_in_enabled)
values (1, 'Restaurante Nicolasa', '5491112345678', true, true);


-- 3. Orders Table
create table public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text,
  order_type text, -- 'eat-in' or 'delivery' or 'takeaway'
  status text default 'pending', -- 'pending', 'completed', 'cancelled'
  total numeric not null,
  items jsonb -- Stores the array of items: [{name, price, quantity}]
);

-- No RLS for now to allow anonymous read/write (since it's a kiosk/demo).
-- IN PRODUCTION: Enable RLS and setup policies using Supabase Auth.
